import sanitizeHtml from "sanitize-html";

type Note = { title: string; content: string; tags: { tag: { name: string } }[]; attachments: { id: string; url: string; filename: string; kind: "IMAGE" | "FILE" }[]; resources: { id: string; label: string; url: string }[] };

export function NoteView({ note }: { note: Note }) {
  const cleanContent = sanitizeHtml(note.content, { allowedTags: ["p", "br", "strong", "em", "s", "h2", "h3", "ul", "ol", "li", "blockquote", "a", "img"], allowedAttributes: { a: ["href", "target", "rel"], img: ["src", "alt"] }, allowedSchemes: ["http", "https"] });
  const hasSidebar = note.resources.length > 0 || note.attachments.length > 0;
  return <div className={hasSidebar ? "note-detail-layout" : "note-detail-layout no-sidebar"}><article className="prose note-article"><p className="eyebrow">LEARNING NOTE</p><h1>{note.title}</h1><p className="tags">{note.tags.map(item => item.tag.name).join(" · ")}</p><div className="note-content" dangerouslySetInnerHTML={{ __html: cleanContent }} /></article>{hasSidebar && <aside className="note-sidebar" aria-label="Note resources"><div className="sidebar-heading"><span>REFERENCE</span><h2>Links & attachments</h2></div>{note.resources.length > 0 && <section className="sidebar-section"><h3>Useful links</h3><ul className="sidebar-link-list">{note.resources.map(resource => <li key={resource.id}><a href={resource.url} target="_blank" rel="noreferrer"><span>{resource.label}</span><small>Open ↗</small></a></li>)}</ul></section>}{note.attachments.length > 0 && <section className="sidebar-section"><h3>Attachments</h3><div className="sidebar-attachments">{note.attachments.map(attachment => attachment.kind === "IMAGE" ? <a key={attachment.id} href={attachment.url} target="_blank" rel="noreferrer" className="attachment-card"><img src={attachment.url} alt={attachment.filename} /><span>{attachment.filename}</span></a> : <a key={attachment.id} href={attachment.url} target="_blank" rel="noreferrer" className="file-card"><span className="file-icon">PDF</span><span>{attachment.filename}</span></a>)}</div></section>}</aside>}</div>;
}
