"use client";

import { useEffect, useState } from "react";
import { RichTextEditor } from "./RichTextEditor";

const api = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000/api";
type Resource = { label: string; url: string };
export type EditableNote = { id: string; title: string; content: string; status: "DRAFT" | "PUBLISHED"; updatedAt: string; tags: { tag: { name: string } }[]; resources: Resource[] };

export function NoteEditor({ token, note, onSaved }: { token: string; note?: EditableNote; onSaved: () => void }) {
  const [title, setTitle] = useState(""); const [content, setContent] = useState("<p>Start writing your note…</p>"); const [tags, setTags] = useState(""); const [status, setStatus] = useState<"DRAFT" | "PUBLISHED">("DRAFT"); const [resources, setResources] = useState<Resource[]>([]); const [resource, setResource] = useState<Resource>({ label: "", url: "" }); const [file, setFile] = useState<File | null>(null); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false); const [persistedId, setPersistedId] = useState<string | null>(null);
  useEffect(() => { setTitle(note?.title ?? ""); setContent(note?.content ?? "<p>Start writing your note…</p>"); setTags(note?.tags.map(item => item.tag.name).join(", ") ?? ""); setStatus(note?.status ?? "DRAFT"); setResources(note?.resources ?? []); setFile(null); setPersistedId(note?.id ?? null); setMessage(""); }, [note]);
  const payload = (overrideStatus = status) => ({ title, content, status: overrideStatus, tags: tags.split(",").map(tag => tag.trim()).filter(Boolean), resources });
  function addResource() { try { new URL(resource.url); } catch { return setMessage("Add a valid resource URL."); } if (!resource.label.trim()) return setMessage("Add a label for the resource."); setResources(current => [...current, { label: resource.label.trim(), url: resource.url.trim() }]); setResource({ label: "", url: "" }); }
  async function uploadFile(noteId: string, image: File) { const form = new FormData(); form.append("file", image); const response = await fetch(`${api}/uploads/${noteId}`, { method: "POST", headers: { Authorization: `Bearer ${token}` }, body: form }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Image upload failed"); return result.url as string; }
  async function uploadInlineImage(image: File) { try { let noteId = persistedId ?? note?.id; if (!noteId) { if (!title.trim()) { setMessage("Add a title before inserting an image."); return null; } setMessage("Saving a draft before uploading the image…"); const response = await fetch(`${api}/notes`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify(payload("DRAFT")) }); const draft = await response.json(); if (!response.ok) throw new Error(draft.error ?? "Could not create draft"); noteId = String(draft.id); setPersistedId(noteId); } const url = await uploadFile(noteId as string, image); setMessage("Image uploaded and inserted. Save the note to publish the updated content."); return url; } catch (error) { setMessage(error instanceof Error ? error.message : "Image upload failed"); return null; } }
  async function save() { setMessage(""); setSaving(true); try { const noteId = persistedId ?? note?.id; const response = await fetch(noteId ? `${api}/notes/${noteId}` : `${api}/notes`, { method: noteId ? "PUT" : "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify(payload()) }); const saved = await response.json(); if (!response.ok) throw new Error(saved.error ?? "Could not save note"); setPersistedId(saved.id); if (file) await uploadFile(saved.id, file); setMessage(noteId ? "Note updated." : "Note created."); onSaved(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not save note"); } finally { setSaving(false); } }
  return <section className="admin-shell"><div className="editor-heading"><div><p className="eyebrow">EDITOR</p><h1>{note || persistedId ? "Edit note" : "Create a learning note"}</h1><p>Format ideas richly, add useful links, and publish when ready.</p></div><div className={`status-pill ${status.toLowerCase()}`}>{status.toLowerCase()}</div></div><div className="editor-grid"><div className="compose-card"><label>Title<input value={title} onChange={event => setTitle(event.target.value)} placeholder="What did you learn?" /></label><label>Tags<input value={tags} onChange={event => setTags(event.target.value)} placeholder="react, databases, design" /></label><RichTextEditor value={content} onChange={setContent} onImageUpload={uploadInlineImage} /><div className="editor-actions"><select value={status} onChange={event => setStatus(event.target.value as typeof status)} aria-label="Publication status"><option value="DRAFT">Save as draft</option><option value="PUBLISHED">Publish now</option></select><button type="button" className="btn-primary" onClick={save} disabled={saving}>{saving ? "Saving…" : note || persistedId ? "Update note" : "Save note"}</button></div>{message && <p className="form-message">{message}</p>}</div><aside className="side-panel"><section><h2>Resources & links</h2><p>Keep references separate from your note body.</p><input value={resource.label} onChange={event => setResource(current => ({ ...current, label: event.target.value }))} placeholder="Resource title" /><input value={resource.url} onChange={event => setResource(current => ({ ...current, url: event.target.value }))} placeholder="https://example.com" /><button type="button" className="secondary" onClick={addResource}>Add resource</button><ul className="resource-list">{resources.map((item, index) => <li key={`${item.url}-${index}`}><a href={item.url} target="_blank" rel="noreferrer">{item.label}</a><button type="button" aria-label={`Remove ${item.label}`} onClick={() => setResources(current => current.filter((_, position) => position !== index))}>×</button></li>)}</ul></section><section><h2>Attachment</h2><p>Upload one image or PDF as a separate downloadable attachment.</p><input type="file" accept="image/png,image/jpeg,image/webp,image/gif,application/pdf" onChange={event => setFile(event.target.files?.[0] ?? null)} />{file && <small>{file.name}</small>}</section></aside></div></section>;
}
